application: pittfashionshare
version: 1
runtime: python27
api_version: 1
threadsafe: false

handlers:

- url: /static
  static_dir: static/
  
- url: /js
  static_dir: static/js

- url: /images
  static_dir: static/images

- url: /.*
  script: main.app